### ISSUE TITLE
Issues with compiling the project

### ISSUE THREAD

**Issue by rlloretb** [fontanf/knapsacksolver#1]
Salut Florian, ça va?

We have issues compiling this project (Windows 11, Visual Studio 2019).
We encounter bind2nd and mem_fun no longer being supported in newer C++ versions.

`PS C:\Users\Pasca\Desktop\knapsacksolver> bazel build  --verbose_failures //python:knapsacksolver.so
WARNING: while reading option defaults file 'c:\users\pasca\desktop\knapsacksolver\.bazelrc':
  invalid command name 'echo'.
WARNING: while reading option defaults file 'c:\users\pasca\desktop\knapsacksolver\.bazelrc':
  invalid command name 'echo'.
WARNING: while reading option defaults file 'c:\users\pasca\desktop\knapsacksolver\.bazelrc':
  invalid command name 'echo'.
INFO: Analyzed target //python:knapsacksolver.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/pasca/desktop/knapsacksolver/knapsacksolver/algorithms/BUILD:124:11: Compiling knapsacksolver/algorithms/bellman.cpp failed: (Exit 2): cl.exe failed: error executing command
  cd /d C:/users/pasca/_bazel_pasca/pew4ifnh/execroot/__main__
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\Pasca\AppData\Local\Temp
    SET TMP=C:\Users\Pasca\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/bin /Iexternal/optimizationtools /Ibazel-out/x64_windows-opt/bin/external/optimizationtools /Iexternal/json /Ibazel-out/x64_windows-opt/bin/external/json /Ibazel-out/x64_windows-opt/bin/external/json/_virtual_includes/json /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /std:c++latest /Fobazel-out/x64_windows-opt/bin/knapsacksolver/algorithms/_objs/bellman/bellman.obj /c knapsacksolver/algorithms/bellman.cpp
# Configuration: 6933d94e9fd1de3542dd7b00af1b432484d3fa768156416469aa665c9cda71a2
# Execution platform: @local_config_platform//:host
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C2039: 'bind2nd': is not a member of 'std'
bazel-out/x64_windows-opt/bin/external/json/_virtual_includes/json\nlohmann/json.hpp(22631): note: see declaration of 'std'
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C2039: 'mem_fun': is not a member of 'std'
bazel-out/x64_windows-opt/bin/external/json/_virtual_includes/json\nlohmann/json.hpp(22631): note: see declaration of 'std'
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C3861: 'mem_fun': identifier not found
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C3861: 'bind2nd': identifier not found
.\knapsacksolver/part_solution_1.hpp(62): warning C4319: '~': zero extending 'unsigned long' to 'const knapsacksolver::PartSol1' of greater size
ERROR: C:/users/pasca/desktop/knapsacksolver/knapsacksolver/BUILD:3:11: Compiling knapsacksolver/solution.cpp failed: (Exit 2): cl.exe failed: error executing command
  cd /d C:/users/pasca/_bazel_pasca/pew4ifnh/execroot/__main__
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\Pasca\AppData\Local\Temp
    SET TMP=C:\Users\Pasca\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/bin /Iexternal/optimizationtools /Ibazel-out/x64_windows-opt/bin/external/optimizationtools /Iexternal/json /Ibazel-out/x64_windows-opt/bin/external/json /Ibazel-out/x64_windows-opt/bin/external/json/_virtual_includes/json /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /std:c++latest /Fobazel-out/x64_windows-opt/bin/knapsacksolver/_objs/knapsacksolver/solution.obj /c knapsacksolver/solution.cpp
# Configuration: 6933d94e9fd1de3542dd7b00af1b432484d3fa768156416469aa665c9cda71a2
# Execution platform: @local_config_platform//:host
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C2039: 'bind2nd': is not a member of 'std'
bazel-out/x64_windows-opt/bin/external/json/_virtual_includes/json\nlohmann/json.hpp(22631): note: see declaration of 'std'
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C2039: 'mem_fun': is not a member of 'std'
bazel-out/x64_windows-opt/bin/external/json/_virtual_includes/json\nlohmann/json.hpp(22631): note: see declaration of 'std'
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C3861: 'mem_fun': identifier not found
external/optimizationtools\optimizationtools/utils/info.hpp(181): error C3861: 'bind2nd': identifier not found
Target //python:knapsacksolver.so failed to build
INFO: Elapsed time: 2.966s, Critical Path: 2.64s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully```

**Comment by fontanf** [comment]
Hi. Sorry, I totally missed this issue, I didn't receive an email for it. Please let me know if you're still interested in it
